Repository MegaMek/mekhq, pull requests merged in 2020-11, with the labels that each got.

#2192 Issue #2188: Cannot assign salary to LAM Pilots or Vehicle Crew loading older CPNX files
  MekHQ/src/mekhq/Utilities.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
Labels: bug

#2198 Issue #785 SLDF Ranks are Wrong
  MekHQ/data/universe/ranks.xml
  MekHQ/src/mekhq/campaign/personnel/Ranks.java
Labels: data

#2215 Add JaCoCo code coverage plugin to test Gradle task
  .github/workflows/ci.yml
  MekHQ/build.gradle
Labels: enhancement

#2218 Issue #2217 #2219: Cannot save Campaign with Refits and cannot start new Refits
  MekHQ/src/mekhq/campaign/parts/Refit.java
Labels: bug

#2230 Issue #2166: NRE in Money::plus/Money::minus
  MekHQ/src/mekhq/campaign/finances/Money.java
  MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
Labels: bug

#2224 Add some basic Refit tests and fix an Armor location bug
  MekHQ/src/mekhq/campaign/parts/Refit.java
  MekHQ/unittests/mekhq/campaign/parts/PartTest.java
  MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
  MekHQ/unittests/mekhq/campaign/unit/UnitTestUtilities.java
Labels: Tests, bug, refit

#2227 Add basic AmmoStorage tests
  MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
  MekHQ/src/mekhq/campaign/parts/InfantryAmmoStorage.java
  MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
  MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
Labels: Tests, bug

#2241 Fix bug where PartsStore may list INT_MAX as cost and tons for BA ammo
  MekHQ/src/mekhq/campaign/market/PartsStore.java
  MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
Labels: bug
