Repository MegaMek/mekhq, pull requests merged in 2021-02, with the labels that each got.

#2409 Issue #2396: Resolve Infantry part and other part type bugs
  MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
  MekHQ/src/mekhq/campaign/parts/Armor.java
  MekHQ/src/mekhq/campaign/parts/BaArmor.java
  MekHQ/src/mekhq/campaign/parts/InfantryAmmoStorage.java
  MekHQ/src/mekhq/campaign/parts/InfantryArmorPart.java
  MekHQ/src/mekhq/campaign/parts/ProtomekArmor.java
  MekHQ/src/mekhq/campaign/parts/SVArmor.java
  MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
  MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorEquipmentPart.java
  MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
  MekHQ/src/mekhq/campaign/parts/equipment/InfantryAmmoBin.java
  MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
  MekHQ/src/mekhq/campaign/parts/equipment/MissingAmmoBin.java
  MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
Labels: bug

#2413 Fixing BaseDialog Preferences
  MekHQ/src/mekhq/gui/dialog/BaseDialog.java
Labels: bug, gui

#2437 Hangar Report: Fixing wrong node addition for medium wheeled
  MekHQ/src/mekhq/campaign/report/HangarReport.java
Labels: bug

#2381 Repair Tab: Adding better information blockers for Null/Void Signature System and Chameleon Shield
  MekHQ/src/mekhq/campaign/parts/MekLocation.java
  MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java
  MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
Labels: bug

#2444 2442: Fixing Multiple Ranks Issues
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
  MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
Labels: Blocker, Ranks, bug
