Repository MegaMek/mekhq, pull requests merged in 2021-03, with the labels that each got.

#2350 Moving Maxmimum d6 to MekHQ Constants instead of CampaignOptions
  MekHQ/src/mekhq/MekHqConstants.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Labels: Refactoring

#2420 Issue #2418: Ensure context menu shortcut works on our tables
  MekHQ/src/mekhq/gui/BriefingTab.java
  MekHQ/src/mekhq/gui/CommandCenterTab.java
  MekHQ/src/mekhq/gui/FinancesTab.java
  MekHQ/src/mekhq/gui/HangarTab.java
  MekHQ/src/mekhq/gui/PersonnelTab.java
  MekHQ/src/mekhq/gui/RepairTab.java
  MekHQ/src/mekhq/gui/TOETab.java
  MekHQ/src/mekhq/gui/WarehouseTab.java
  MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java
  MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/ScenarioTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Labels: Accessibility

#2361 Use MML's CConfig.load instead of new CConfig()
  MekHQ/src/mekhq/gui/MekLabTab.java
Labels: enhancement

#2416 2415: Implementing Unit Weapon SPA Generation and Fixing Tech Level Comparisons
  MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java
  MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
  MekHQ/src/mekhq/campaign/personnel/generator/SingleSpecialAbilityGenerator.java
Labels: Personnel, bug, enhancement

#2260 Implementing Save and Quit in the MekHQ exit option pane
  MekHQ/src/mekhq/MekHQ.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
Labels: enhancement, gui

#2451 Issue #2446: Calculate the scrollable block increment correctly
  MekHQ/src/mekhq/gui/view/ScrollablePanel.java
Labels: Accessibility, Stable Backport Candidate

#2453 Issue #2452: Ensure a Lance's Force assignment is still valid
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/force/Lance.java
Labels: AtB, Stable Backport Candidate, bug

#2349 Removing unused camo property file
  MekHQ/resources/mekhq/resources/CamoChoiceDialog.properties
  ReadMe.md
Labels: enhancement

#2337 Shopping List No Longer Writes to XML While Empty and Cleanup
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/market/ShoppingList.java
  MekHQ/src/mekhq/gui/CommandCenterTab.java
Labels: Refactoring, enhancement

#2151 MissionStatus Enum
  MekHQ/resources/mekhq/resources/Mission.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignSummary.java
  MekHQ/src/mekhq/campaign/force/Lance.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/market/ContractMarket.java
  MekHQ/src/mekhq/campaign/market/UnitMarket.java
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/mission/Contract.java
  MekHQ/src/mekhq/campaign/mission/Mission.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/enums/MissionStatus.java
  MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
  MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
  MekHQ/src/mekhq/gui/BriefingTab.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
  MekHQ/src/mekhq/gui/dialog/CompleteMissionDialog.java
  MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
  MekHQ/src/mekhq/gui/dialog/ShipSearchDialog.java
  MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
  MekHQ/src/mekhq/gui/view/MissionViewPanel.java
  MekHQ/unittests/mekhq/campaign/market/ContractMarketIntegrationTest.java
  MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
Labels: Refactoring, enhancement

#2461 Issue #2459: Only calculate weight if EquipmertPart has a type
  MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
Labels: Stable Backport Candidate, bug

#2463 2458: MRMS Astech Requirement Checks
  MekHQ/resources/mekhq/resources/MassRepair.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
  MekHQ/src/mekhq/gui/model/DocTableModel.java
  MekHQ/src/mekhq/service/MassRepairService.java
Labels: Mass Repair/Mass Salvage, enhancement

#2473 Better unit restore
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/campaign/unit/actions/RestoreUnitAction.java
  MekHQ/unittests/mekhq/campaign/unit/actions/RestoreUnitActionTest.java
Labels: enhancement

#2475 Use the correct resource string for free C3i Nodes on TOE
  MekHQ/src/mekhq/gui/ForceRenderer.java
Labels: Stable Backport Candidate, bug

#2464 2456: Incorrect Financial Export Date, Two Force Icon NPEs, Unit Market NPE
  MekHQ/resources/mekhq/resources/Finances.properties
  MekHQ/src/mekhq/MHQStaticDirectoryManager.java
  MekHQ/src/mekhq/Utilities.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/finances/Finances.java
  MekHQ/src/mekhq/campaign/finances/enums/FinancialYearDuration.java
  MekHQ/src/mekhq/campaign/market/UnitMarket.java
  MekHQ/unittests/mekhq/campaign/finances/enums/FinancialYearDurationTest.java
Labels: bug

#2471 2469: Fixing Award Log Edit NPEs
  MekHQ/resources/mekhq/resources/AddOrEditPersonnelEntryDialog.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/campaign/log/AwardLogEntry.java
  MekHQ/src/mekhq/campaign/log/AwardLogger.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/control/EditPersonnelLogControl.java
  MekHQ/src/mekhq/gui/dialog/AddOrEditPersonnelEntryDialog.java
Labels: bug, enhancement

#2470 Java 11 Migration and isBlank Cleanup
  MekHQ/src/mekhq/MHQStaticDirectoryManager.java
  MekHQ/src/mekhq/campaign/GamePreset.java
  MekHQ/src/mekhq/campaign/finances/Currency.java
  MekHQ/src/mekhq/campaign/personnel/generator/RandomPortraitGenerator.java
  MekHQ/src/mekhq/gui/dialog/ScenarioTemplateEditorDialog.java
  MekHQ/src/mekhq/io/AwardFileFactory.java
  MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
  MekHQ/unittests/mekhq/campaign/parts/InfantryAmmoStorageTest.java
  MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/AmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/BattleArmorAmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/EquipmentPartTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/InfantryAmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/LargeCraftAmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/MissingAmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/MissingEquipmentPartTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/MissingInfantryAmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBinTest.java
Labels: enhancement

#2477 338: Base Free Time Sort
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/RepairTab.java
  MekHQ/src/mekhq/gui/WarehouseTab.java
  MekHQ/src/mekhq/gui/model/TaskTableModel.java
  MekHQ/src/mekhq/service/MassRepairService.java
Labels: enhancement

#2468 Bulk Procurement Table Selection and GM-less Clear
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/gui/CommandCenterTab.java
  MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java
  MekHQ/src/mekhq/gui/model/ProcurementTableModel.java
Labels: enhancement

#2393 3288: GM Tool Name Generation Expansion - Bulk Generation, Manual Editing
  MekHQ/resources/mekhq/resources/GMToolsDialog.properties
  MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
Labels: enhancement

#2371 1936: AbstractIcon: Full Camouflage Implementation - Adding Force Camouflage
  MekHQ/resources/mekhq/resources/CampaignGUI.properties
  MekHQ/src/mekhq/AtBGameThread.java
  MekHQ/src/mekhq/GameThread.java
  MekHQ/src/mekhq/MekHqXmlUtil.java
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
  MekHQ/src/mekhq/campaign/force/Force.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/BotForce.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
  MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
  MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
  MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Labels: Refactoring, enhancement
