Repository MegaMek/mekhq, pull requests merged in 2021-12, with the labels that each got.

#2989 Watford: Equipment Unscrambling Testability Refactor
  MekHQ/src/mekhq/Utilities.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/parts/Refit.java
  MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
  MekHQ/src/mekhq/campaign/unit/cleanup/ApproximateMatchStep.java
  MekHQ/src/mekhq/campaign/unit/cleanup/BattleArmorEquipmentProposal.java
  MekHQ/src/mekhq/campaign/unit/cleanup/BattleArmorEquipmentUnscrambler.java
  MekHQ/src/mekhq/campaign/unit/cleanup/DefaultEquipmentUnscrambler.java
  MekHQ/src/mekhq/campaign/unit/cleanup/EquipmentProposal.java
  MekHQ/src/mekhq/campaign/unit/cleanup/EquipmentProposalReport.java
  MekHQ/src/mekhq/campaign/unit/cleanup/EquipmentUnscrambler.java
  MekHQ/src/mekhq/campaign/unit/cleanup/EquipmentUnscramblerResult.java
  MekHQ/src/mekhq/campaign/unit/cleanup/ExactMatchStep.java
  MekHQ/src/mekhq/campaign/unit/cleanup/MovedAmmoBinStep.java
  MekHQ/src/mekhq/campaign/unit/cleanup/MovedEquipmentStep.java
  MekHQ/src/mekhq/campaign/unit/cleanup/UnscrambleStep.java
  MekHQ/unittests/mekhq/campaign/unit/cleanup/ApproximateMatchStepTest.java
  MekHQ/unittests/mekhq/campaign/unit/cleanup/EquipmentProposalTest.java
  MekHQ/unittests/mekhq/campaign/unit/cleanup/EquipmentUnscramblerTest.java
  MekHQ/unittests/mekhq/campaign/unit/cleanup/ExactMatchStepTest.java
  MekHQ/unittests/mekhq/campaign/unit/cleanup/MovedAmmoBinTest.java
  MekHQ/unittests/mekhq/campaign/unit/cleanup/MovedEquipmentStepTest.java
Labels: Enhancement, Repair/Refit

#2991 MM 3289: Removing IPlayer Interface
  MekHQ/build.gradle
  MekHQ/testresources/mockito-extensions/org.mockito.plugins.MockMaker
  MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
  MekHQ/unittests/mekhq/campaign/universe/FactionBorderTrackerTest.java
  MekHQ/unittests/mekhq/campaign/universe/FactionBordersTest.java
Labels: Refactoring

#2986 Fixing Unit Market Preference Copy/Paste Error
  MekHQ/resources/mekhq/resources/Market.properties
Labels: Bug

#2999 Fixing Quirk Exception
  MekHQ/src/mekhq/GameThread.java
Labels: Blocker

#3004 JUnit Update to 4.13.2 from 4.12
  MekHQ/build.gradle
Labels: Enhancement

#2720 MM 2199: MUL Parser Game Option-reliant Personnel Load
  MekHQ/src/mekhq/MekHqXmlUtil.java
  MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/BotForce.java
  MekHQ/src/mekhq/campaign/mission/Scenario.java
  MekHQ/src/mekhq/campaign/parts/Refit.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/campaign/unit/UnitOrder.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
Labels: Bug, Personnel

#2864 2863: Adding Dates Personnel Tab Filter, Displaying Dates, and adding Pregnancy Colour
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
  MekHQ/resources/mekhq/resources/PersonnelTableModel.properties
  MekHQ/src/mekhq/MekHQOptions.java
  MekHQ/src/mekhq/MekHqConstants.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/gui/PersonnelTab.java
  MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
  MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
  MekHQ/src/mekhq/gui/enums/PersonnelTabView.java
  MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
  MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Labels: Enhancement, Personnel

#3016 Fixing Unit Testing Issues
  MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
Labels: Bug

#2851 Personnel Modules: Marriage: Modularization and Expanded Options
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/Personnel.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/enums/MergingSurnameStyle.java
  MekHQ/src/mekhq/campaign/personnel/enums/RandomMarriageMethod.java
  MekHQ/src/mekhq/campaign/personnel/familyTree/Genealogy.java
  MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java
  MekHQ/src/mekhq/campaign/personnel/marriage/DisabledRandomMarriage.java
  MekHQ/src/mekhq/campaign/personnel/marriage/PercentageRandomMarriage.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
  MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
  MekHQ/src/mekhq/gui/utilities/StaticChecks.java
  MekHQ/unittests/mekhq/campaign/personnel/familyTree/GenealogyTest.java
Labels: Enhancement, Personnel, GUI

#2908 Personnel Modules: Divorce: Modularization, Random Divorce, Expanded Options, and Bulk Manual Divorce
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/Personnel.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
  MekHQ/src/mekhq/campaign/personnel/divorce/DisabledRandomDivorce.java
  MekHQ/src/mekhq/campaign/personnel/divorce/PercentageRandomDivorce.java
  MekHQ/src/mekhq/campaign/personnel/enums/Divorce.java
  MekHQ/src/mekhq/campaign/personnel/enums/RandomDivorceMethod.java
  MekHQ/src/mekhq/campaign/personnel/enums/SplittingSurnameStyle.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
Labels: Enhancement, Personnel

#3017 PersonnelTableModelColumn Enum
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/PersonnelTableModel.properties
  MekHQ/src/mekhq/gui/PersonnelTab.java
  MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
  MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
  MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
  MekHQ/src/mekhq/gui/enums/PersonnelTabView.java
  MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
  MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
Labels: Enhancement, Personnel

#2812 Switching Person to be fully pass-by-reference with regards to Campaign
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
  MekHQ/src/mekhq/campaign/finances/Accountant.java
  MekHQ/src/mekhq/campaign/finances/Finances.java
  MekHQ/src/mekhq/campaign/market/PersonnelMarketRandom.java
  MekHQ/src/mekhq/campaign/mod/am/InjuryTypes.java
  MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
  MekHQ/src/mekhq/campaign/personnel/generator/AbstractSkillGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/AbstractSpecialAbilityGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/DefaultSpecialAbilityGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/SingleSpecialAbilityGenerator.java
  MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
  MekHQ/src/mekhq/campaign/report/PersonnelReport.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
  MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
  MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
  MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
  MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
  MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
  MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
  MekHQ/src/mekhq/gui/model/RetirementTableModel.java
  MekHQ/src/mekhq/gui/model/UnitTableModel.java
  MekHQ/src/mekhq/gui/view/ForceViewPanel.java
  MekHQ/unittests/mekhq/campaign/personnel/PersonTest.java
  MekHQ/unittests/mekhq/campaign/rating/FieldManualMercRevDragoonsRatingTest.java
Labels: Refactoring

#3022 Fixing missing files in the Windows MHQ build
  MekHQ/build.gradle
Labels: Blocker

#3024 Track additional characteristics in Scenario
  MekHQ/build.gradle
  MekHQ/resources/mekhq/resources/ScenarioViewPanel.properties
  MekHQ/src/mekhq/AtBGameThread.java
  MekHQ/src/mekhq/GameThread.java
  MekHQ/src/mekhq/MekHQ.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/BotForce.java
  MekHQ/src/mekhq/campaign/mission/BotForceRandomizer.java
  MekHQ/src/mekhq/campaign/mission/Scenario.java
  MekHQ/src/mekhq/campaign/mission/ScenarioDeploymentLimit.java
  MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
  MekHQ/src/mekhq/gui/BriefingTab.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
  MekHQ/src/mekhq/gui/view/ScenarioViewPanel.java
Labels: Refactoring

#3032 Properly reset legacy log file
  MekHQ/src/mekhq/MekHQ.java
Labels: Blocker

#3031 Force Icons: Fixing Frame Duplication on Load
  MekHQ/src/mekhq/campaign/icons/LayeredForceIcon.java
Labels: Blocker

#3035 2983: Reordering spouse KIA logging so it is assigned to the correct person
  MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
Labels: Bug, Personnel

#3036 2993: Fixing Duplicated Small Craft and JumpShip Pilot Assignment
  MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
Labels: Bug, Personnel
