Repository MegaMek/mekhq, pull requests merged in 2021-01, with the labels that each got.

#2320 1727: Colour Camouflage
  MekHQ/src/mekhq/AtBGameThread.java
  MekHQ/src/mekhq/MekHqXmlUtil.java
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/BotForce.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/gui/BasicInfo.java
  MekHQ/src/mekhq/gui/PlanetarySystemMapPanel.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/CamoChoiceDialog.java
  MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
  MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
  MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
  MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
  MekHQ/src/mekhq/gui/model/RetirementTableModel.java
  MekHQ/src/mekhq/gui/model/UnitAssignmentTableModel.java
  MekHQ/src/mekhq/gui/model/UnitTableModel.java
  MekHQ/src/mekhq/gui/view/ForceViewPanel.java
  MekHQ/src/mekhq/gui/view/UnitViewPanel.java
Labels: Major, bug, enhancement

#2293 Upgrades built in campaigns to 0.47.15
  MekHQ/campaigns/Fist and Falcon/Binary Bravo, 1st Falcon Strikers.cpnx
  MekHQ/campaigns/Fist and Falcon/Kewran Wolfhounds, C Company, 3rd Battalion, 25th Arcturan Guards RCT.cpnx
  MekHQ/campaigns/Sword and Dragon/Fox's Teeth, McKinnon's Company, Vausur's Battalion, Seventh Crucis Lancers RCT.cpnx
  MekHQ/campaigns/Sword and Dragon/Sorenson Sabres, Jisatsu Company, Otomo, formerly Third Company, Tarwater's Battalion, Fifth Sword of Light.cpnx
  MekHQ/campaigns/Wolf and Blake/Black Widow Company, Church's Independent Company, Wolf's Dragoons.cpnx
  MekHQ/campaigns/Wolf and Blake/Shadow Hunters, Opacus Venatori, Fifty-second Shadow Division.cpnx
Labels: data

#2344 Issue #2341: Equipment on incorrect mounts is not fixed
  MekHQ/src/mekhq/Utilities.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Labels: bug, refit

#2354 Don't skip ComStar as an origin faction
  MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
Labels: bug

#2355 Issue #2348: Allow Clanner origins
  MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
Labels: bug, enhancement

#2367 Colour Camouflage: Fixing Colour Camouflage Tint Application and Colour Setter
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/mission/BotForce.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Labels: bug

#2372 Infantry Motive Type File I/O Fixes
  MekHQ/src/mekhq/campaign/parts/InfantryMotiveType.java
  MekHQ/src/mekhq/campaign/parts/MissingInfantryMotiveType.java
Labels: bug

#2378 Acquisition Dialog: Fixing NPE, GM Acquire for In-Transit or On Order parts, Adding GM Acquire Message
  MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
Labels: bug

#2391 2389: Fixing graphical NPE when not purchasing units in the unit selector dialog
  MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
Labels: bug

#2390 Fixing Baby Prisoner Status Ternary
  MekHQ/src/mekhq/campaign/personnel/Person.java
Labels: bug

#2399 2397: Adding Fall Back SPA check for current SPAs being edited
  MekHQ/src/mekhq/gui/dialog/EditSpecialAbilityDialog.java
Labels: bug
