Repository MegaMek/mekhq, pull requests merged in 2022-02, with the labels that each got.

#3103 3102: Fixing Contract Completion Retirement ConMod
  MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
Labels: Bug, AtB

#3007 Skill Generation: Phenotype Bonus Applies to Proper Skills
  MekHQ/src/mekhq/campaign/personnel/generator/AbstractSkillGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java
Labels: Bug, Personnel

#3020 New Campaign Project: Campaign Options Pane
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/gui/SpecialAbilityPanel.java
  MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
  MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Labels: GUI, Refactoring

#3099 Remove bad logic from check on preventing breakthrough
  MekHQ/data/scenariotemplates/Harass.xml
  MekHQ/data/scenariotemplates/Prevent Breakthrough.xml
  MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
Labels: AtB, Scenario Resolution

#3109 Fix incorrect tag on xml output
  MekHQ/src/mekhq/campaign/personnel/Skill.java
Labels: Bug

#3121 BLOCKER: Replacing MHQ's Startup GUI with a modified version of MML's
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/StartUpDialog.properties
  MekHQ/src/mekhq/MekHQ.java
  MekHQ/src/mekhq/gui/StartUpGUI.java
  MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
Labels: GUI, Blocker

#3122 BLOCKER: Read the font directory for MHQ instead of ignoring it.
  MekHQ/src/mekhq/MekHQ.java
Labels: GUI, Blocker

#3117 Adding Build-Date to the Manifest File
  MekHQ/build.gradle
Labels: Enhancement

#3116 Adding the Legendary SkillLevel
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
Labels: Enhancement, Personnel

#3107 Standardized Suite Graphical Setup Initialization: Font and Theme Standardization
  MekHQ/src/mekhq/MekHQ.java
Labels: Refactoring

#3125 MML Standardized Directory Setup Changes
  MekHQ/src/mekhq/MekHQ.java
  MekHQ/src/mekhq/campaign/parts/Refit.java
  MekHQ/src/mekhq/gui/BriefingTab.java
  MekHQ/src/mekhq/gui/MekLabTab.java
  MekHQ/src/mekhq/gui/dialog/MekHQAboutBox.java
Labels: Enhancement

#3128 Build Script and Integration Issues: Standardization and Fixes
  .github/codecov.yml
  .github/workflows/ci.yml
  .github/workflows/code-coverage.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/nightly-ci.yml
  MekHQ/build.gradle
  MekHQ/src/mekhq/campaign/personnel/enums/FamilialRelationshipType.java
  build.gradle
Labels: Enhancement

#3131 3130: Fixing Unit Order File I/O Copypaste Bug
  MekHQ/src/mekhq/campaign/unit/UnitOrder.java
Labels: Bug

#3134 Standardized Code Utilities
  MekHQ/src/mekhq/MekHqXmlUtil.java
  MekHQ/src/mekhq/Utilities.java
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/finances/Loan.java
  MekHQ/src/mekhq/campaign/force/UnitStub.java
  MekHQ/src/mekhq/campaign/log/PersonalLogger.java
  MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/BotForceRandomizer.java
  MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifier.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
  MekHQ/src/mekhq/campaign/mod/am/HitLocationGen.java
  MekHQ/src/mekhq/campaign/personnel/Clan.java
  MekHQ/src/mekhq/campaign/personnel/Injury.java
  MekHQ/src/mekhq/campaign/personnel/InjuryType.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/enums/MergingSurnameStyle.java
  MekHQ/src/mekhq/campaign/personnel/generator/AbstractSkillGenerator.java
  MekHQ/src/mekhq/campaign/personnel/generator/SingleSpecialAbilityGenerator.java
  MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
  MekHQ/src/mekhq/campaign/stratcon/StratconFacilityFactory.java
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
  MekHQ/src/mekhq/campaign/stratcon/StratconScenarioFactory.java
  MekHQ/src/mekhq/campaign/unit/actions/HirePersonnelUnitAction.java
  MekHQ/src/mekhq/campaign/universe/News.java
  MekHQ/src/mekhq/campaign/universe/NewsItem.java
  MekHQ/src/mekhq/campaign/universe/Planet.java
  MekHQ/src/mekhq/campaign/universe/PlanetarySystem.java
  MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
  MekHQ/src/mekhq/campaign/universe/StarUtil.java
  MekHQ/src/mekhq/gui/DailyReportLogPanel.java
  MekHQ/src/mekhq/gui/InterstellarMapPanel.java
  MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
  MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
  MekHQ/src/mekhq/gui/dialog/NewPlanetaryEventDialog.java
  MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
  MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
  MekHQ/src/mekhq/gui/menus/AssignUnitToTechMenu.java
  MekHQ/src/mekhq/gui/model/RetirementTableModel.java
  MekHQ/src/mekhq/module/atb/AtBEventProcessor.java
  MekHQ/src/mekhq/service/AutosaveService.java
Labels: Refactoring

#3136 3097: Adding Medical Dialog Handwriting Font Selection Option
  MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
  MekHQ/src/mekhq/MHQConstants.java
  MekHQ/src/mekhq/MHQOptions.java
  MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
  MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
Labels: Bug, Accessibility, Personnel, GUI

#3137 Fixing the final two LGTM issues
  MekHQ/src/mekhq/campaign/force/ForceStub.java
  MekHQ/src/mekhq/gui/PlanetarySystemMapPanel.java
Labels: Enhancement

#3113 AbstractIcon: MHQ's Preferences Now Write to MekHQ's File
  MekHQ/src/mekhq/gui/dialog/AbstractMHQIconChooserDialog.java
  MekHQ/src/mekhq/gui/dialog/iconDialogs/StandardForceIconDialog.java
  MekHQ/src/mekhq/gui/dialog/iconDialogs/UnitIconDialog.java
  MekHQ/src/mekhq/gui/panels/AbstractMHQIconChooser.java
  MekHQ/src/mekhq/gui/panels/ForcePieceIconChooser.java
  MekHQ/src/mekhq/gui/panels/StandardForceIconChooser.java
  MekHQ/src/mekhq/gui/panels/UnitIconChooser.java
Labels: Bug, GUI

#3133 3132: Adding Entity Generation Null Protection for Officer Duel Scenario
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
Labels: Bug, AtB

#3123 Company Generator: Adding MechWarrior Callsign Generation Option
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/campaign/universe/companyGeneration/CompanyGenerationOptions.java
  MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
  MekHQ/src/mekhq/gui/panels/CompanyGenerationOptionsPanel.java
Labels: Enhancement

#3105 Base Components: CompleteMissionDialog Rewrite
  MekHQ/resources/mekhq/resources/CompleteMissionDialog.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/gui/BriefingTab.java
  MekHQ/src/mekhq/gui/dialog/CompleteMissionDialog.java
Labels: Enhancement

#2892 2877: Part XML File I/O using MekHqXmlUtil
  MekHQ/src/mekhq/campaign/parts/Part.java
  MekHQ/src/mekhq/campaign/work/WorkTime.java
  MekHQ/unittests/mekhq/campaign/parts/equipment/LargeCraftAmmoBinTest.java
Labels: Enhancement
