Repository MegaMek/mekhq, pull requests merged in 2024-11, with the labels that each got.

#5151 Fixed Line Breaks in StratCon Facility Descriptions
  MekHQ/data/stratconfacilities/AlliedAirBase.xml
  MekHQ/data/stratconfacilities/AlliedArtilleryBase.xml
  MekHQ/data/stratconfacilities/AlliedBaseOfOperations.xml
  MekHQ/data/stratconfacilities/AlliedCommsCenter.xml
  MekHQ/data/stratconfacilities/AlliedMekBase.xml
  MekHQ/data/stratconfacilities/AlliedTankBase.xml
  MekHQ/data/stratconfacilities/HostileAirBase.xml
  MekHQ/data/stratconfacilities/HostileArtilleryBase.xml
  MekHQ/data/stratconfacilities/HostileBaseOfOperations.xml
  MekHQ/data/stratconfacilities/HostileDataCenter.xml
  MekHQ/data/stratconfacilities/HostileIndustrialFacility.xml
  MekHQ/data/stratconfacilities/HostileMekBase.xml
  MekHQ/data/stratconfacilities/HostileOrbitalDefense.xml
  MekHQ/data/stratconfacilities/HostileTankBase.xml
Labels: Bug, StratCon

#5154 Renamed Tracks and AtB Campaign State in StratCon
  MekHQ/resources/mekhq/resources/CampaignGUI.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
  MekHQ/src/mekhq/gui/StratconPanel.java
  MekHQ/src/mekhq/gui/StratconTab.java
Labels: StratCon, UX

#5156 Refactor Supply Depot SP Modifiers to be Monthly
  MekHQ/data/stratconfacilities/AlliedSupplyDepot.xml
  MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Labels: StratCon

#5157 Fixed StratCon Reinforcement Deployment Check
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Labels: Bug, StratCon

#5163 Added Force BV Multiplier Logging & Adjusted Calculation in `AtBDynamicScenarioFactory`
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Labels: Force Generation

#5167 [FG3] Updated Infantry Generation Method and Trainee Settings
  MekHQ/data/scenariomodifiers/AlliedTraineesAir.xml
  MekHQ/data/scenariomodifiers/AlliedTraineesGround.xml
  MekHQ/data/scenariomodifiers/LocalGarrisonInfantry.xml
  MekHQ/data/scenariotemplates/Irregular Force Assault.xml
  MekHQ/data/scenariotemplates/Irregular Force Suppression.xml
Labels: Bug, Force Generation

#5168 [FG3] StratCon will No Longer Display GBV when Using FG3
  MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java
Labels: Bug, StratCon

#5172 Added Contract Automation
  MekHQ/resources/mekhq/resources/Campaign.properties
  MekHQ/resources/mekhq/resources/ContractAutomation.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/market/contractMarket/ContractAutomation.java
  MekHQ/src/mekhq/campaign/mission/Contract.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
Labels: UX

#5174 Updated Faction Loading Log Format
  MekHQ/src/mekhq/campaign/universe/Factions.java
Labels: Bug

#5175 Temporarily Disabled Preset Confirm in New Campaign Dialog
  MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
Labels: Campaign Options

#5176 Temporarily Removed CAM_OPS from Contract Market Method ComboBox
  MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Labels: Campaign Options

#5179 Fix Perm. Injury showing as Injury on Personnel tabel
  MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
Labels: Personnel

#5180 Show refitting techs and fix refit countdown
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
Labels: Parts/Repair/Refit

#5208 Handled Exception when Fetching Force by ID in `StratconPanel`
  MekHQ/src/mekhq/gui/StratconPanel.java
Labels: Bug, StratCon

#5211 Reduced Force Multiplier for Pirate Scenarios
  MekHQ/data/scenariomodifiers/PiratesIncomingAir.xml
  MekHQ/data/scenariomodifiers/PiratesIncomingGround.xml
  MekHQ/data/scenariomodifiers/PiratesPresentAir.xml
  MekHQ/data/scenariomodifiers/PiratesPresentGround.xml
Labels: Force Generation

#5212 Fix Spouse Dependency Check in Divorce Logic.
  MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
Labels: Bug, Personnel

#5213 Enhanced Mothballing in `ContractAutomation`
  MekHQ/src/mekhq/campaign/market/contractMarket/ContractAutomation.java
Labels: Bug

#5214 Corrected Unit Site Comparison Logic
  MekHQ/src/mekhq/campaign/Campaign.java
Labels: Bug

#5215 Refactored `getCurrentPrisoners` to use `getActivePersonnel`
  MekHQ/src/mekhq/campaign/Campaign.java
Labels: Bug, Personnel

#5216 Reputation Error Corrections & Report Reformatting
  MekHQ/resources/mekhq/resources/CamOpsReputation.properties
  MekHQ/src/mekhq/campaign/rating/CamOpsReputation/CommandRating.java
  MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java
  MekHQ/src/mekhq/campaign/rating/CamOpsReputation/TransportationRating.java
Labels: Bug, Unit Rating

#5217 Enhanced INVALID Formation Level Checking
  MekHQ/src/mekhq/campaign/force/FormationLevel.java
Labels: Bug

#5222 Lowered Capture Percentage Requirement to 25%
  MekHQ/data/scenariomodifiers/FacilityHostileCapture.xml
  MekHQ/data/scenariomodifiers/FacilityHostileCaptureNonWin.xml
Labels: StratCon

#5223 Adjusted Command Rights Scenario Modifiers
  MekHQ/data/scenariomodifiers/HouseOfficerAir.xml
  MekHQ/data/scenariomodifiers/HouseOfficerGround.xml
  MekHQ/data/scenariomodifiers/IntegratedAlliesAir.xml
  MekHQ/data/scenariomodifiers/IntegratedAlliesGround.xml
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
Labels: Force Generation

#5224 Updated Force Generation for Irregular Scenarios
  MekHQ/data/scenariotemplates/Irregular Force Assault.xml
  MekHQ/data/scenariotemplates/Irregular Force Suppression.xml
Labels: Force Generation

#5225 Removed Legacy AtB Guaranteed SPAs
  MekHQ/src/mekhq/campaign/personnel/generator/DefaultSpecialAbilityGenerator.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
Labels: AtB

#5227 Renamed "Add Funds" to "Add Transaction" for Clarity
  MekHQ/docs/Stratcon and Against the Bot/AtB documentation.19_8 (WIP).txt
  MekHQ/resources/mekhq/resources/AddFundsDialog.properties
  MekHQ/src/mekhq/gui/FinancesTab.java
Labels: GUI

#5228 Added Monthly StratCon Support Points Generation
  MekHQ/resources/mekhq/resources/Campaign.properties
  MekHQ/src/mekhq/campaign/Campaign.java
Labels: StratCon

#5234 Refined Turnover Prompt Dialog Text
  MekHQ/resources/mekhq/resources/Campaign.properties
Labels: GUI

#5242 Fix Typo and Added `null` check in `RetirementDefectionTracker`
  MekHQ/resources/mekhq/resources/RetirementDefectionTracker.properties
  MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
Labels: Bug, Personnel

#5243 Updated MekHQ Morale & StratCon Scenario Spawn Methods
  MekHQ/docs/Stratcon and Against the Bot/MekHQ Morale.pdf
  MekHQ/resources/mekhq/resources/Campaign.properties
  MekHQ/resources/mekhq/resources/ContractMarketDialog.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java
  MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
  MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java
  MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
  MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
Labels: StratCon, Refactoring, Documentation

#5247 [FG3] Updated Aircraft Force Generation, Unit Culling, and Added ProtoMeks
  MekHQ/data/scenariotemplates/Low-Atmosphere DropShip Escort.xml
  MekHQ/data/scenariotemplates/Space Blockade Run.xml
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/unittests/mekhq/campaign/mission/DynamicScenarioFactoryTest.java
Labels: Force Generation

#5253 allows to select a previous engineer or new crew member to activate large vessels
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/unit/MothballInfo.java
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
  MekHQ/unittests/mekhq/campaign/CampaignTest.java
Labels: Bug

#5250 Renamed 'Lances' to 'Strategic Formations', Expanded Functionality
  MekHQ/src/mekhq/AtBGameThread.java
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/force/Force.java
  MekHQ/src/mekhq/campaign/force/StrategicFormation.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
  MekHQ/src/mekhq/campaign/mission/AtBScenario.java
  MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/ChaseBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/ExtractionBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/HideAndSeekBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/HoldTheLineBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/ProbeBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/ReconRaidBuiltInScenario.java
  MekHQ/src/mekhq/campaign/mission/atb/scenario/StandUpBuiltInScenario.java
  MekHQ/src/mekhq/campaign/personnel/autoAwards/MiscAwards.java
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
  MekHQ/src/mekhq/gui/BriefingTab.java
  MekHQ/src/mekhq/gui/ForceRenderer.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java
  MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
  MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
Labels: Force Generation
