Repository MegaMek/mekhq, pull requests merged in 2025-02, with the labels that each got.

#5949 Clarify Vocational XP Tooltip
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Labels: Bug, GUI

#5931 Refactored Part Handling in Resupply Module
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
  MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
Labels: Improvement to Existing Feature

#5952 Fixed Cargo Capacity Calculation in For Cargo Items in Body
  MekHQ/src/mekhq/campaign/unit/Unit.java
Labels: Bug

#5954 Further Improvements to Cargo Container Checks; added Unit Tests
  MekHQ/src/mekhq/campaign/unit/Unit.java
  MekHQ/unittests/mekhq/campaign/unit/GetCargoCapacityTest.java
Labels: Bug, Tests

#5852 RAW CamOps Delivery Times
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/EquipmentAndSuppliesTab.java
Labels: Implementation of Missing Official Rule

#5853 Remove Legacy AtB's Campaign Parts Availability System
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
Labels: AtB, Finances, Legacy Improvement

#5868 Updated Several Scenario Effects to use `SupplyCache` over `SupportPointUpdate`
  MekHQ/data/scenariomodifiers/FacilityHostileExtract.xml
  MekHQ/data/scenariotemplates/Convoy Interdiction.xml
  MekHQ/data/scenariotemplates/Convoy Raid.xml
  MekHQ/src/mekhq/campaign/mission/ObjectiveEffect.java
  MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
Labels: AtB, StratCon, Improvement to Existing Feature

#5871 Refactored Personnel Cleanup and Random Dependent Removal
  MekHQ/resources/mekhq/resources/Campaign.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/personnel/familyTree/Genealogy.java
Labels: Bug

#5873 Added Force Type Enumeration
  MekHQ/resources/mekhq/resources/ForceType.properties
  MekHQ/src/mekhq/campaign/force/CombatTeam.java
  MekHQ/src/mekhq/campaign/force/Force.java
  MekHQ/src/mekhq/campaign/force/ForceType.java
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
  MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/ResupplyUtilities.java
  MekHQ/src/mekhq/gui/ForceRenderer.java
  MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogContractStart.java
  MekHQ/src/mekhq/gui/utilities/StaticChecks.java
  MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Labels: Refactoring, Utility

#5892 Refactored Resupply Messaging to use Internalization
  MekHQ/resources/mekhq/resources/Resupply.properties
  MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogAbandonedConvoy.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogContractStart.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogInterception.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogItinerary.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogPlayerConvoyOption.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogResupplyFocus.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogRoleplayEvent.java
  MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogSwindled.java
Labels: Refactoring

#5905 Refactored Currency to No Longer Always Display as C-Bills
  MekHQ/data/universe/currencies.xml
  MekHQ/resources/mekhq/resources/CampaignExportWizard.properties
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/Finances.properties
  MekHQ/resources/mekhq/resources/FinancesTab.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/RetirementDefectionDialog.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/finances/Currency.java
  MekHQ/src/mekhq/campaign/finances/CurrencyManager.java
  MekHQ/src/mekhq/campaign/finances/Finances.java
  MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
Labels: GUI, Refactoring

#5920 MegaMekLab Issue 1703: Allow bays to be added to aerospace fighters
  MekHQ/src/mekhq/gui/MekLabTab.java
Labels: GUI

#5955 Implemented Death Rework
  MekHQ/docs/Personnel Modules/Random Death in MekHQ.pdf
  MekHQ/mmconf/campaignPresets/CampaignOperations.xml
  MekHQ/mmconf/campaignPresets/CampaignOperationsStratCon.xml
  MekHQ/mmconf/campaignPresets/NewPilotProgram.xml
  MekHQ/mmconf/campaignPresets/TheCompleteExperience.xml
  MekHQ/resources/mekhq/resources/CampaignGUI.properties
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/resources/mekhq/resources/Personnel.properties
  MekHQ/resources/mekhq/resources/RandomDeath.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/personnel/death/AbstractDeath.java
  MekHQ/src/mekhq/campaign/personnel/death/AgeRangeRandomDeath.java
  MekHQ/src/mekhq/campaign/personnel/death/DisabledRandomDeath.java
  MekHQ/src/mekhq/campaign/personnel/death/ExponentialRandomDeath.java
  MekHQ/src/mekhq/campaign/personnel/death/PercentageRandomDeath.java
  MekHQ/src/mekhq/campaign/personnel/death/RandomDeath.java
  MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
  MekHQ/src/mekhq/campaign/personnel/enums/RandomDeathMethod.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java
  MekHQ/unittests/mekhq/campaign/personnel/death/AbstractDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/death/AgeRangeRandomDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/death/DisabledRandomDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/death/ExponentialRandomDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/death/PercentageRandomDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/death/RandomDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/enums/RandomDeathMethodTest.java
Labels: Personnel, Tests, Refactoring, Documentation, New Feature

#5959 Updated `rankSystems` version to `0.50.04-SNAPSHOT`
  MekHQ/userdata/data/universe/ranks.xml
Labels: Refactoring

#5962 Converted Honor Rating into an Enum
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/universe/Faction.java
  MekHQ/src/mekhq/campaign/universe/enums/HonorRating.java
Labels: Refactoring

#5964 Use `ModifiedConstantSkillGenerator` for Skill Generation
  MekHQ/src/mekhq/campaign/mission/BotForceRandomizer.java
  MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
Labels: Refactoring

#5965 Added "Intercept the Escapees" Scenario Template
  MekHQ/data/scenariotemplates/Intercept the Escapees.xml
  MekHQ/src/mekhq/campaign/mission/enums/ScenarioType.java
Labels: New Feature

#5966 Added 'None' Generation Method to `ScenarioForceTemplate`
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
Labels: Improvement to Existing Feature

#5981 Issue 5845: In Stratcon scenario wizard, leadership units consider transport assignments
  MekHQ/resources/mekhq/resources/AssignForceToTransport.properties
  MekHQ/resources/mekhq/resources/AtBStratCon.properties
  MekHQ/src/mekhq/campaign/utilities/CampaignTransportUtilities.java
  MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Labels: (RFE) Enhancement, StratCon

#5989 fix: local bots property empty on non-atb games
  MekHQ/src/mekhq/GameThread.java
Labels: Bug

#5907 Implemented Clarion Note & Gray Monday
  MekHQ/mmconf/campaignPresets/CampaignOperations.xml
  MekHQ/mmconf/campaignPresets/CampaignOperationsStratCon.xml
  MekHQ/mmconf/campaignPresets/NewPilotProgram.xml
  MekHQ/mmconf/campaignPresets/TheCompleteExperience.xml
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/GrayMonday.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
  MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java
  MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java
  MekHQ/src/mekhq/campaign/mission/Contract.java
  MekHQ/src/mekhq/campaign/randomEvents/GrayMonday.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java
  MekHQ/src/mekhq/gui/dialog/DateChooser.java
  MekHQ/src/mekhq/gui/dialog/randomEvents/GrayMondayDialog.java
Labels: New Feature

#5963 Refactored `PrisonerStatus` Enum and Reorganized Related Code
  MekHQ/resources/mekhq/resources/PrisonerStatus.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/enums/PrisonerStatus.java
  MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java
  MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
  MekHQ/src/mekhq/campaign/randomEvents/prisoners/enums/PrisonerStatus.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/PersonnelTab.java
  MekHQ/src/mekhq/gui/sorter/PrisonerStatusSorter.java
  MekHQ/unittests/mekhq/campaign/personnel/PersonTest.java
  MekHQ/unittests/mekhq/campaign/personnel/death/AbstractDeathTest.java
  MekHQ/unittests/mekhq/campaign/personnel/divorce/AbstractDivorceTest.java
  MekHQ/unittests/mekhq/campaign/personnel/enums/PrisonerStatusTest.java
  MekHQ/unittests/mekhq/campaign/personnel/marriage/AbstractMarriageTest.java
  MekHQ/unittests/mekhq/campaign/personnel/procreation/AbstractProcreationTest.java
  MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/enums/PrisonerStatusTest.java
  MekHQ/unittests/mekhq/gui/dialog/nagDialogs/nagLogic/UntreatedPersonnelNagLogicTest.java
Labels: Tests, Refactoring

#5990 Corrected `randomDeathMultiplier` to use Double
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java
Labels: Bug

#5997 Refactored `getAllUnits` to Simplify Logic and Added Unit Tests
  MekHQ/src/mekhq/campaign/force/Force.java
  MekHQ/unittests/mekhq/campaign/force/ForceTest.java
Labels: Bug, Tests

#5993 Adjusted Gray Monday Employer Dialog to Trigger on the Correct Day
  MekHQ/src/mekhq/campaign/randomEvents/GrayMonday.java
  MekHQ/src/mekhq/gui/dialog/randomEvents/GrayMondayDialog.java
Labels: Bug, GUI

#5999 Fixed Clan Ghost Bear Greeting Keys
  MekHQ/resources/mekhq/resources/FameAndInfamy.properties
Labels: Bug, GUI

#6001 Added Glossary Functionality to `MHQDialogImmersive` with Clickable Hyperlink Support
  MekHQ/resources/mekhq/resources/Glossary.properties
  MekHQ/src/mekhq/gui/baseComponents/MHQDialogImmersive.java
  MekHQ/src/mekhq/gui/dialog/GlossaryDialog.java
  MekHQ/src/mekhq/gui/dialog/VocationalExperienceAwardDialog.java
  MekHQ/src/mekhq/utilities/MHQInternationalization.java
  MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/enums/PrisonerStatusTest.java
Labels: GUI, UX, Utility

#6004 Refactored Support Point Modification Method Name
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
  MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
  MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
  MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
Labels: Refactoring

#6005 Refactored Fatigue Modification Method Name
  MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java
  MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Labels: Refactoring

#6006 Added Shortcut Method to Check if a Unit is Battle Armor
  MekHQ/src/mekhq/campaign/unit/Unit.java
Labels: Utility

#6014 Refactored Active Personnel Retrieval Logic
  MekHQ/src/mekhq/campaign/Campaign.java
Labels: Refactoring

#6013 Refactored Random Dependents Removal-Addition into a Seperate Class
  MekHQ/resources/mekhq/resources/Campaign.properties
  MekHQ/resources/mekhq/resources/RandomDependents.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/personnel/RandomDependents.java
  MekHQ/unittests/mekhq/campaign/personnel/RandomDependentsTest.java
Labels: Personnel, Refactoring

#6051 Read user force icons data from user directory
  MekHQ/docs/UserDirHelp.html
  MekHQ/src/mekhq/MHQConstants.java
  MekHQ/src/mekhq/MHQStaticDirectoryManager.java
Labels: UX

#6068 Enhancement - Allow Battle Armor suits from different squad sizes to be used as replacements
  MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
  MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
Labels: (RFE) Enhancement

#6082 Fixed File Path Separator for `RandomEventLibraries` on Windows
  MekHQ/src/mekhq/campaign/randomEvents/RandomEventLibraries.java
  MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonEscapeScenario.java
Labels: Bug, Severity: Critical

#6083 Adjusted Prisoner Capacity Calculations and Event Logic
  MekHQ/docs/Stratcon and Against the Bot/Prisoners of War & Abstracted Search and Rescue.pdf
  MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java
Labels: Refactoring, Documentation

#5998 Personality Revamp
  MekHQ/docs/Personnel Modules/Random Personalities.pdf
  MekHQ/resources/mekhq/resources/Aggression.properties
  MekHQ/resources/mekhq/resources/Ambition.properties
  MekHQ/resources/mekhq/resources/Greed.properties
  MekHQ/resources/mekhq/resources/Intelligence.properties
  MekHQ/resources/mekhq/resources/Personalities.properties
  MekHQ/resources/mekhq/resources/PersonalityQuirk.properties
  MekHQ/resources/mekhq/resources/Social.properties
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
  MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/PersonalityController.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/enums/personalities/Aggression.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/enums/personalities/Ambition.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/enums/personalities/Greed.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/enums/personalities/Intelligence.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/enums/personalities/PersonalityQuirk.java
  MekHQ/src/mekhq/campaign/personnel/randomEvents/enums/personalities/Social.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/PersonalityController.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Aggression.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Ambition.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Greed.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Intelligence.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/PersonalityQuirk.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Social.java
  MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java
  MekHQ/src/mekhq/campaign/rating/CamOpsReputation/CommandRating.java
  MekHQ/src/mekhq/campaign/storyarc/storypoint/CreateCharacterStoryPoint.java
  MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
  MekHQ/src/mekhq/gui/dialog/CreateCharacterDialog.java
  MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
  MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
  MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
  MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
  MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
  MekHQ/src/mekhq/utilities/MHQInternationalization.java
  MekHQ/unittests/mekhq/campaign/randomEvents/personalities/enums/AggressionTest.java
  MekHQ/unittests/mekhq/campaign/randomEvents/personalities/enums/AmbitionTest.java
  MekHQ/unittests/mekhq/campaign/randomEvents/personalities/enums/GreedTest.java
  MekHQ/unittests/mekhq/campaign/randomEvents/personalities/enums/IntelligenceTest.java
  MekHQ/unittests/mekhq/campaign/randomEvents/personalities/enums/PersonalityQuirkTest.java
  MekHQ/unittests/mekhq/campaign/randomEvents/personalities/enums/SocialTest.java
Labels: Bug, Personnel, Tests, Documentation
