Repository MegaMek/mekhq, pull requests merged in 2025-06, with the labels that each got.

#7162 Improvement: Added Helper Method to Make Testing Real Campaign Objects Easy
  MekHQ/src/mekhq/campaign/utilities/TestableCampaign.java
  MekHQ/unittests/mekhq/campaign/utilities/TestableCampaignTest.java
Labels: Tests, Utility

#7174 Improvement: #4204 #6865 Improved Accessibility of Market Options
  MekHQ/resources/mekhq/resources/CampaignGUI.properties
  MekHQ/resources/mekhq/resources/GUI.properties
  MekHQ/src/mekhq/MHQConstants.java
  MekHQ/src/mekhq/MHQOptions.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/CommandCenterTab.java
  MekHQ/src/mekhq/gui/HangarTab.java
  MekHQ/src/mekhq/gui/PersonnelTab.java
  MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java
  MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
Labels: GUI, UX

#7173 Fix/rolling logs
  MekHQ/mmconf/log4j2.xml
  MekHQ/src/mekhq/campaign/personnel/enums/Phenotype.java
  MekHQ/src/mekhq/campaign/work/IPartWork.java
Labels: Bug

#7182 fix: multiple small and simple fixes, reenable planet search, fix npe…
  .github/workflows/ci.yml
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
  MekHQ/src/mekhq/campaign/market/PartsStore.java
  MekHQ/src/mekhq/campaign/mission/enums/CombatRole.java
  MekHQ/src/mekhq/campaign/parts/Part.java
  MekHQ/src/mekhq/campaign/parts/VeeStabilizer.java
  MekHQ/src/mekhq/campaign/personnel/Person.java
  MekHQ/src/mekhq/campaign/personnel/SkillPrerequisite.java
  MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
  MekHQ/src/mekhq/gui/MapTab.java
  MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java
  MekHQ/src/mekhq/gui/dialog/EditSkillPreRequisiteDialog.java
  MekHQ/src/mekhq/gui/dialog/EditSpecialAbilityDialog.java
  MekHQ/src/mekhq/utilities/spaUtilities/SpaUtilities.java
Labels: Bug, Blocker

#7192 Fix: #7165 Fixed Typo in Faction Standing Options Label
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Labels: Bug, GUI, Campaign Options, Severity: Low

#7191 Fix: #7179 Fixed Typo in Intra-Unit Marriage Campaign Option
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Labels: Bug, GUI, Campaign Options, Severity: Low

#7193 Fix: #7151 Fixed Typos in Convoy Escort Scenarios
  MekHQ/data/scenariotemplates/Close Air Support.xml
  MekHQ/data/scenariotemplates/Convoy Escort.xml
  MekHQ/data/scenariotemplates/Critical Convoy Escort.xml
Labels: Bug, GUI, Severity: Low

#7206 Fix: #7072 Corrected Tooltip Panel Size in Finance Tab
  MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java
Labels: Bug, GUI, Campaign Options, Severity: High

#7205 Fix: #7074 Corrected Typo in Briefing Room Tutorial Panel
  MekHQ/resources/mekhq/resources/ContractViewPanel.properties
Labels: Bug, GUI, Severity: Low

#7202 Improvement: #7197 Added Noble & Common Criminal Civilian Professions
  MekHQ/resources/mekhq/resources/PersonnelRole.properties
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
Labels: Personnel, Improvement to Existing Feature

#7200 Improvement: #7196 Improved Civilian Generation to Include Better Control Over Random Profession Selection
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsUtilities.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/PersonnelTab.java
Labels: Personnel, Campaign Options, Improvement to Existing Feature

#7194 Fix: #7142 Cleaned Up Profession Assignments to Prevent Invalid Assignments
  MekHQ/src/mekhq/campaign/personnel/Person.java
Labels: Bug, Personnel, Severity: Medium

#7189 Fix: #7185 Fixed Mothballed Units Teleporting to Already Deployed Forces
  MekHQ/src/mekhq/campaign/unit/MothballInfo.java
Labels: Bug, StratCon, Severity: Medium

#7207 Improvement: #7184 Updated Campaign Options Preset Picker to Improve Visual Scaling
  MekHQ/resources/mekhq/resources/CampaignOptionsPresetPicker.properties
  MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsDialog.java
  MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPresetPicker.java
  MekHQ/src/mekhq/gui/campaignOptions/SelectPresetDialog.java
  MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
Labels: GUI, UX

#7225 Fix: Fixed Typo in Recruiter Notes for Aggression Variant 1 Personality Trait
  MekHQ/resources/mekhq/resources/Aggression.properties
Labels: Bug, GUI, Severity: Low

#7230 Improvement: Added Cancel Button to the New Player Quickstart Dialog; Allowed for Resizing of Dialog
  MekHQ/resources/mekhq/resources/NewPlayerQuickstartDialog.properties
  MekHQ/src/mekhq/gui/dialog/NewPlayerQuickstartDialog.java
  MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
Labels: GUI, UX

#7226 Fix: #7166 Fixed Displayed Applicant in New Personnel Market Lagging Behind Selection When Using Directional Keys
  MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Labels: Bug, GUI, Severity: Medium

#7221 Improvement: #7220 Loosened Applicant Experience Level Clamping in New Personnel Market
  MekHQ/src/mekhq/campaign/market/personnelMarket/markets/PersonnelMarketMekHQ.java
Labels: UX

#7215 Fix: #7156 Fixed Golden Hello in New Personnel Market Not Remembering Last Setting
  MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Labels: Bug, Severity: Medium

#7213 Improvement: Rebranded Administrative Strain as HR Strain to Reduce Confusion
  MekHQ/resources/mekhq/resources/CampaignGUI.properties
  MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
  MekHQ/resources/mekhq/resources/FullGlossaryDialog.properties
  MekHQ/resources/mekhq/resources/Glossary.properties
  MekHQ/resources/mekhq/resources/NagDialogs.properties
  MekHQ/resources/mekhq/resources/RetirementDefectionTracker.properties
  MekHQ/src/mekhq/MHQConstants.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/CampaignSummary.java
  MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
  MekHQ/src/mekhq/gui/CommandCenterTab.java
  MekHQ/src/mekhq/gui/campaignOptions/contents/TurnoverAndRetentionTab.java
  MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
  MekHQ/src/mekhq/gui/dialog/nagDialogs/HRStrainNagDialog.java
  MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
  MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/HRStrainNagLogic.java
  MekHQ/unittests/mekhq/gui/dialog/nagDialogs/nagLogic/HRStrainNagLogicTest.java
Labels: GUI, UX

#7214 Improvement: New Personnel Market Dialog Will Now Remember Last Size
  MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Labels: GUI, UX

#7260 Improvement: Allowed Users to Resize Immersive Dialogs
  MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogCore.java
Labels: GUI, UX

#7258 Improvement: Added Aggregate Faction Tag
  MekHQ/src/mekhq/campaign/universe/Faction.java
  MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandings.java
  MekHQ/src/mekhq/gui/dialog/factionStanding/gmToolsDialog/FactionSelectionDialog.java
  MekHQ/src/mekhq/gui/dialog/factionStanding/manualMissionDialogs/SimulateMissionDialog.java
Labels: Utility

#7240 Improvement: Depreciated BatchallFactions.java
  MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
  MekHQ/src/mekhq/campaign/universe/factionStanding/BatchallFactions.java
Labels: Utility

#7241 Improvement: Implements Faction Standing-based Batchall Modifiers
  MekHQ/resources/mekhq/resources/PerformBatchall.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/mission/AtBContract.java
  MekHQ/src/mekhq/campaign/universe/factionStanding/PerformBatchall.java
Labels: Improvement to Existing Feature

#7238 Improvement: Implemented Faction Standing-based Negotiation Modifiers
  MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
  MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java
Labels: Improvement to Existing Feature

#7239 Improvement: Implemented Faction Standing-based Resupply Weight Modifiers
  MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
Labels: Improvement to Existing Feature

#7242 Improvement: Implements Faction Standing-based Food & Housing Cost Modifiers; Fixed Bug with Food & Housing Costs
  MekHQ/src/mekhq/campaign/finances/Accountant.java
  MekHQ/src/mekhq/campaign/finances/Finances.java
Labels: Bug, Severity: Medium, Improvement to Existing Feature

#7243 Improvement: Implements Faction Standing-based Contract Pay; Added Pay Modifier for Clan Campaigns Pre-Tukayyid
  MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
Labels: Improvement to Existing Feature

#7244 Improvement: Implements Faction Standing-based Support Point Generation Modifiers
  MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
Labels: Improvement to Existing Feature

#7246 Improvement: Implements Faction Standing-based Recruitment Modifiers
  MekHQ/src/mekhq/campaign/market/personnelMarket/markets/PersonnelMarketMekHQ.java
Labels: Improvement to Existing Feature

#7267 Improvement: Changed Location of Pronoun Data Class for Ease of Access
  MekHQ/src/mekhq/campaign/personnel/PronounData.java
  MekHQ/src/mekhq/campaign/personnel/lifeEvents/BirthAnnouncement.java
  MekHQ/src/mekhq/campaign/personnel/lifeEvents/ComingOfAgeAnnouncement.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/PersonalityController.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Aggression.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Ambition.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Greed.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/PersonalityQuirk.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Reasoning.java
  MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Social.java
Labels: Refactoring, Utility

#7265 Fix: Adjusted Active Faction Getter to Optionally Exclude 'Command' Factions
  MekHQ/src/mekhq/campaign/universe/Faction.java
  MekHQ/src/mekhq/campaign/universe/Factions.java
Labels: Bug, Utility, Severity: Low

#7252 Improvement: Implemented Faction Standings and Contract Outlawing
  MekHQ/resources/mekhq/resources/Campaign.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandingUtilities.java
  MekHQ/src/mekhq/gui/InterstellarMapPanel.java
Labels: Improvement to Existing Feature

#7251 Improvement: Implemented Command Circuit Travel via GM Mode or Faction Standings
  MekHQ/resources/mekhq/resources/CampaignGUI.properties
  MekHQ/src/mekhq/campaign/Campaign.java
  MekHQ/src/mekhq/campaign/CampaignOptions.java
  MekHQ/src/mekhq/campaign/CurrentLocation.java
  MekHQ/src/mekhq/campaign/JumpPath.java
  MekHQ/src/mekhq/campaign/mission/Contract.java
  MekHQ/src/mekhq/campaign/universe/PlanetarySystem.java
  MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandingUtilities.java
  MekHQ/src/mekhq/gui/CampaignGUI.java
  MekHQ/src/mekhq/gui/MapTab.java
  MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
  MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
  MekHQ/src/mekhq/gui/view/JumpPathViewPanel.java
  MekHQ/src/mekhq/gui/view/PlanetViewPanel.java
Labels: UX, Improvement to Existing Feature

#7279 Improvement: Added Faction Leadership Tracking to Faction Overhaul
  MekHQ/src/mekhq/campaign/universe/Faction.java
Labels: Data, Improvement to Existing Feature
